/**
 * Marketing product snapshots — framed assets match native aspect (no side-crop).
 * Regenerated by: node scripts/crop-snapshots.mjs
 */

import aspects from "./snapshot-aspects.json";

export type SnapshotId =
  | "dash"
  | "sites"
  | "site-dash"
  | "agent"
  | "agent-main"
  | "reports"
  | "perf"
  | "security"
  | "seo"
  | "billing"
  | "settings"
  | "backup"
  | "plugin";

export interface SnapshotMeta {
  id: SnapshotId;
  src: string;
  darkSrc?: string;
  alt: string;
  label: string;
  caption: string;
  aspect: string;
  href?: string;
}

function aspectFor(id: SnapshotId): string {
  return (aspects as Record<string, { aspect: string }>)[id]?.aspect ?? "16 / 10";
}

/** Cache-bust query so Next/browser drop stale optimized WebPs after re-crop */
function srcFor(id: SnapshotId): string {
  const v =
    (aspects as Record<string, { v?: string }>)[id]?.v ?? "1";
  return `/snapshots/framed/${id}.png?v=${v}`;
}

export const SNAPSHOTS: Record<SnapshotId, SnapshotMeta> = {
  dash: {
    id: "dash",
    src: srcFor("dash"),
    alt: "Site Armor agency portfolio dashboard with health scores",
    label: "Portfolio dashboard",
    caption: "One score across every client site",
    aspect: aspectFor("dash"),
    href: "/features",
  },
  sites: {
    id: "sites",
    src: srcFor("sites"),
    alt: "Sites grid with performance, SEO, security, and uptime",
    label: "Sites portfolio",
    caption: "Every site scored at a glance",
    aspect: aspectFor("sites"),
    href: "/features",
  },
  "site-dash": {
    id: "site-dash",
    src: srcFor("site-dash"),
    alt: "Single-site dashboard with pillar score rings",
    label: "Site health",
    caption: "Drill into any client",
    aspect: aspectFor("site-dash"),
    href: "/features",
  },
  agent: {
    id: "agent",
    src: srcFor("agent"),
    alt: "AI Agent chat about portfolio scores",
    label: "AI Agent",
    caption: "Ask it — then confirm the fix",
    aspect: aspectFor("agent"),
    href: "/features/ai-agent",
  },
  "agent-main": {
    id: "agent-main",
    src: srcFor("agent-main"),
    alt: "AI Agent workspace",
    label: "Agent workspace",
    caption: "Portfolio-aware assistant",
    aspect: aspectFor("agent-main"),
    href: "/features/ai-agent",
  },
  reports: {
    id: "reports",
    src: srcFor("reports"),
    alt: "White-label client reports ready to send",
    label: "Client reports",
    caption: "Branded PDFs, ready to send",
    aspect: aspectFor("reports"),
    href: "/features/client-reports",
  },
  perf: {
    id: "perf",
    src: srcFor("perf"),
    alt: "Performance monitoring dashboard",
    label: "Performance",
    caption: "Core Web Vitals & trends",
    aspect: aspectFor("perf"),
    href: "/features/performance-monitoring",
  },
  security: {
    id: "security",
    src: srcFor("security"),
    alt: "Security scanning dashboard",
    label: "Security",
    caption: "Hardening & SSL checks",
    aspect: aspectFor("security"),
    href: "/features/security-scanning",
  },
  seo: {
    id: "seo",
    src: srcFor("seo"),
    alt: "SEO audit dashboard",
    label: "SEO",
    caption: "On-page SEO audits",
    aspect: aspectFor("seo"),
    href: "/features/seo-monitoring",
  },
  billing: {
    id: "billing",
    src: srcFor("billing"),
    alt: "Billing and plans",
    label: "Billing",
    caption: "Plans & usage",
    aspect: aspectFor("billing"),
    href: "/pricing",
  },
  settings: {
    id: "settings",
    src: srcFor("settings"),
    alt: "Agency settings",
    label: "Settings",
    caption: "Agency configuration",
    aspect: aspectFor("settings"),
    href: "/trust",
  },
  backup: {
    id: "backup",
    src: srcFor("backup"),
    alt: "Automated backups with schedule and one-click restore",
    label: "Backups",
    caption: "Schedule & restore in one click",
    aspect: aspectFor("backup"),
    href: "/features/backups",
  },
  plugin: {
    id: "plugin",
    src: srcFor("plugin"),
    alt: "Site Armor WordPress plugin settings — connected and syncing",
    label: "WordPress plugin",
    caption: "Connect a site in about two minutes",
    aspect: aspectFor("plugin"),
    href: "/wordpress-plugin",
  },
};

/** Map feature page slugs → snapshot */
export const FEATURE_SNAPSHOT: Record<string, SnapshotId> = {
  "performance-monitoring": "perf",
  "seo-monitoring": "seo",
  "security-scanning": "security",
  "malware-detection": "security",
  "uptime-monitoring": "dash",
  "ai-agent": "agent",
  "client-reports": "reports",
  "white-label": "reports",
  "client-portal": "reports",
  backups: "backup",
  "plugin-updates": "plugin",
  "broken-link-checker": "sites",
  "woocommerce-monitoring": "dash",
};

export const HERO_FEATURES: SnapshotId[] = [
  "dash",
  "site-dash",
  "agent",
  "reports",
];

export const TOUR_SLIDES: SnapshotId[] = [
  "dash",
  "sites",
  "site-dash",
  "agent",
  "perf",
  "security",
  "seo",
  "reports",
];

/** @deprecated use HERO_FEATURES */
export const HERO_REEL = HERO_FEATURES;

export const PILLAR_SNAPSHOTS: Partial<Record<string, SnapshotId>> = {
  performance: "perf",
  seo: "seo",
  security: "security",
  malware: "security",
  uptime: "dash",
};
